version: '3.7'

services:
  s-mongodb:
    image: mongo:latest
    container_name: c-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    ports:
      - 27017:27017
    volumes:
      - ./scripts/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # s-mailcatcher:
  #   image: dockage/mailcatcher:0.8.2
  #   container_name: c-mailcatcher
  #   ports:
  #     - 5080:1080
  #     - ${MAILER_PORT}:5025