version: '3.9'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel --no-autoupdate run
    env_file:
      - cloudflare.env
  canva-mariadb:
    image: mariadb:latest
    container_name: canva-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example_root_password
      MARIADB_DATABASE: example_database
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", 'mariadb-admin', 'ping', '-h', 'localhost', '-u', 'example_user', '-p','example_password' ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
  #    volumes:
  #      - mariadb_data:/var/lib/mysql
  web-api:
    build: canva-api
    image: canva-api:latest
    container_name: canva-api
    ports:
      - "8888:8080"
    env_file:
      - backend.env
    depends_on:
      - canva-mariadb
  web-frontend:
    build:
      context: .
      dockerfile: canva-app-fe/Dockerfile
    image: canva-app-fe:latest
    container_name: canva-app-fe
    ports:
      - "3000:80"
    depends_on:
      - canva-mariadb

#volumes:
#  mariadb_data: