version: '3.8'

services:
  web-api:
    build: martec-be
    container_name: my-backend-app
    ports:
      - "3000:3000"
    env_file:
      - backend.env.local
  web-frontend:
    build:
      context: .
      dockerfile: martec-fe/Dockerfile
    container_name: my-fe-app
    ports:
      - "5173:80"