version: "3.7"

networks:
  themartec:
    driver: bridge

services:
  postgres:
    image: postgres:14.4-alpine
    container_name: themartec_backend_postgres
    restart: always
    environment:
      - POSTGRES_USER=themartec_backend_development
      - POSTGRES_PASSWORD=cjAEQJs3
      - PGDATA=/var/lib/postgresql/data/themartec_backend/
    ports:
      - '7432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - themartec

#  app:
#    container_name: themartec_backend_backend
#    build:
#      context: ./
#    working_dir: /src
#    environment:
#      - .env
#    ports:
#      - '7000:3000'
#    command: npm start
#    volumes:
#      - ./:/src
#    stdin_open: true
#    tty: true
#    networks:
#      - themartec
#    depends_on:
#      - postgres

  mailcatcher:
    image: schickling/mailcatcher
    container_name: themartec_mailcatcher
    networks:
      - themartec
    ports:
      - "7180:1080"
      - "7125:1025"

volumes:
  db-data:
    driver: local